### ISSUE TITLE
Grunt Task Error Fatal error: fs.emptyDir is not a function

### ISSUE THREAD

**Issue by ethyde** [jonathantneal/mdcss#12] opened 2016-01-30 20:06 UTC
Hi,

I try to add `mdcss` to a Postcss project. But i have the following error `Fatal error: fs.emptyDir is not a function`.

My grunt task

```
postcss: {
    options: {
        processors: [
            require('mdcss')
        ]
    },
    dev: {
        src: 'app/styles/main.css'
    }
}
```

In my package.json

```
"grunt": "^0.4.5",
"grunt-postcss": "^0.7.1",
"mdcss": "^1.5.0",
"mdcss-theme-github": "^2.2.0",
"postcss": "^5.0.14"
```

Thanks for your help ! :)

**Comment by stephenway** [comment] 2016-02-09 23:40
Looks like this is related to #13. I'm also having this issue, currently a blocker for me.

**Comment by jonathantneal** [comment] 2016-02-10 00:48
This is very curious. I’m looking into it right now.

**Comment by jonathantneal** [comment] 2016-02-10 14:32
@stephenway, @ethyde, would you share your node version and os? I’m wondering if `fs-promise` is not resolving to use `fs-extra`. I may need to embed this functionality for now.

**Comment by stephenway** [comment] 2016-02-10 14:38
@jonathantneal: OS X 10.11.1 and Node v5.5.0

**Comment by jonathantneal** [comment] 2016-02-10 15:08
@stephenway, I have pushed a new release [v1.5.1](https://github.com/jonathantneal/mdcss/tree/v1.5.1) that swaps `fs-promise` for an internal method. Please let me know if this resolves the issue. If it does, I will bring it to the attention of the creator of `fs-promise`.

**Comment by ethyde** [comment] 2016-02-10 15:44
@jonathantneal Hi,

Os : Win 10 Pro
Node : v 5.1.1

So I have the following error with version 1.5.1 :
![screen_error_mdcss](https://cloud.githubusercontent.com/assets/409987/12952048/6942c8c8-d015-11e5-99b3-e60e10d18225.jpg)

**Comment by jonathantneal** [comment] 2016-02-10 16:25
This is unrelated to your original error, and seems to be permission related. Would you create a new issue for it? @stephenway, would you let me know how it is working for you?

**Comment by stephenway** [comment] 2016-02-10 18:15
Yea I'm back on 1.4 but I'll upgrade today and test it out.

**Comment by stephenway** [comment] 2016-04-06 17:09
@jonathantneal I just updated to 1.5.1 with the latest default theme and I can confirm that it compiles for me properly. Sorry for the wait.

**Closed as completed** 2016-05-12 20:39 UTC
Labels: awaiting feedback
